
INSERT INTO events( id, title, style, date_hour, max_participants, description, actual_participants) VALUES (default,'Soy el concierto 1', 'rock', '2023-01-12',  300,  'Descripción 1',  100)
INSERT INTO events( id, title, style, date_hour, max_participants, description, actual_participants) VALUES (default,'Soy el concierto 2', 'pop', '2023-01-12',  300,  'Descripción 2',  200)
INSERT INTO events( id, title, style, date_hour, max_participants, description, actual_participants) VALUES (default,'Soy el concierto 3', 'bachata', '2023-01-12',  90,  'Descripción 3',  80)
INSERT INTO events( id, title, style, date_hour, max_participants, description, actual_participants) VALUES (default,'Soy el concierto 4', 'rap', '2023-01-12',  90,  'Descripción 4',  80)
INSERT INTO events( id, title, style, date_hour, max_participants, description, actual_participants) VALUES (default,'Soy el concierto 5', 'ballenato', '2023-01-12',  90,  'Descripción 5',  80)
INSERT INTO users( id, username, password) VALUES (default,'Raul',          ) 
INSERT INTO users( id, username, password) VALUES (default,'GobizConBambas', 'asas22' )
INSERT INTO roles (id, name) VALUES (default,'ROLE_ADMIN')
INSERT INTO roles (id, name) VALUES (default,'ROLE_USER')
INSERT INTO user_roles (user_id, role_id) VALUES (1,1)
